data_ingestion:
  data_output_path: "datas/raw"
  data_url: "https://raw.githubusercontent.com/RAKIBUL424/Datasets/refs/heads/main/job_salary_prediction_dataset.csv"
  test_size: 0.2
  random_state: 42